// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGqyBfMz9-haiT0o1LnH3bJO6iH7mhgpc',
    appId: '1:1000544844870:android:c90b469e33682148dade47',
    messagingSenderId: '1000544844870',
    projectId: 'faravi-erp-dev',
    databaseURL: 'https://faravi-erp-dev-default-rtdb.firebaseio.com',
    storageBucket: 'faravi-erp-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiww9vhAnxvxKQXGC8bbAp7phv9-8frwA',
    appId: '1:1000544844870:ios:ab524d43855c49c7dade47',
    messagingSenderId: '1000544844870',
    projectId: 'faravi-erp-dev',
    databaseURL: 'https://faravi-erp-dev-default-rtdb.firebaseio.com',
    storageBucket: 'faravi-erp-dev.firebasestorage.app',
    iosBundleId: 'com.badargo.qa.badargoTask',
  );
}
